server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerDB
    username: root
    password: Harsh@12345
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  application:
    name: CUSTOMER-SERVICE
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EURECA_SERVER_PORT:8761}/eureka
      fetchRegistry: true
      registerWithEureka: true